In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import polars as pl
import yaml

In [10]:
with open('../config.yaml', 'r') as file:
    config = yaml.safe_load(file)

In [12]:
final_demo = pl.read_csv(config["input_data"]["file1"])
final_demo.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ client_id ┆ clnt_tenu ┆ clnt_tenu ┆ clnt_age ┆ … ┆ num_accts ┆ bal       ┆ calls_6_m ┆ logons_6_ │
│ ---       ┆ re_yr     ┆ re_mnth   ┆ ---      ┆   ┆ ---       ┆ ---       ┆ nth       ┆ mnth      │
│ i64       ┆ ---       ┆ ---       ┆ f64      ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---       │
│           ┆ f64       ┆ f64       ┆          ┆   ┆           ┆           ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 836976    ┆ 6.0       ┆ 73.0      ┆ 60.5     ┆ … ┆ 2.0       ┆ 45105.3   ┆ 6.0       ┆ 9.0       │
│ 2304905   ┆ 7.0       ┆ 94.0      ┆ 58.0     ┆ … ┆ 2.0       ┆ 110860.3  ┆ 6.0       ┆ 9.0       │
│ 1439522   ┆ 5.0       ┆ 64.0      ┆ 32.0     ┆ … ┆ 2.0       ┆ 52467.79  ┆ 6.0       ┆ 9.0       │
│ 1562045   ┆ 16.0      ┆ 198.0     ┆ 49.0     ┆ … ┆ 2.0       ┆ 67454.65  ┆ 3.0       ┆ 6.0       │
│ 5126305   ┆ 12.0      ┆ 145.0     ┆ 33.0     ┆ … ┆ 2.0       ┆ 103671.75 ┆ 0.0       ┆ 3.0       │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
experiment_data = pl.read_csv(config["input_data"]["file2"])
experiment_data.head()

shape: (5, 2)
┌───────────┬───────────┐
│ client_id ┆ Variation │
│ ---       ┆ ---       │
│ i64       ┆ str       │
╞═══════════╪═══════════╡
│ 9988021   ┆ Test      │
│ 8320017   ┆ Test      │
│ 4033851   ┆ Control   │
│ 1982004   ┆ Test      │
│ 9294070   ┆ Control   │
└───────────┴───────────┘

In [15]:
webdata1 = pl.read_csv(config["input_data"]["file3"])
webdata1.head()

shape: (5, 5)
┌───────────┬──────────────────────┬──────────────────────────┬──────────────┬─────────────────────┐
│ client_id ┆ visitor_id           ┆ visit_id                 ┆ process_step ┆ date_time           │
│ ---       ┆ ---                  ┆ ---                      ┆ ---          ┆ ---                 │
│ i64       ┆ str                  ┆ str                      ┆ str          ┆ str                 │
╞═══════════╪══════════════════════╪══════════════════════════╪══════════════╪═════════════════════╡
│ 9988021   ┆ 580560515_7732621733 ┆ 781255054_21935453173_53 ┆ step_3       ┆ 2017-04-17 15:27:07 │
│           ┆                      ┆ 1117                     ┆              ┆                     │
│ 9988021   ┆ 580560515_7732621733 ┆ 781255054_21935453173_53 ┆ step_2       ┆ 2017-04-17 15:26:51 │
│           ┆                      ┆ 1117                     ┆              ┆                     │
│ 9988021   ┆ 580560515_7732621733 ┆ 781255054_21935453173_53 ┆ step_3       ┆ 2017-04-17 15:19:22 │
│           ┆                      ┆ 1117                     ┆              ┆                     │
│ 9988021   ┆ 580560515_7732621733 ┆ 781255054_21935453173_53 ┆ step_2       ┆ 2017-04-17 15:19:13 │
│           ┆                      ┆ 1117                     ┆              ┆                     │
│ 9988021   ┆ 580560515_7732621733 ┆ 781255054_21935453173_53 ┆ step_3       ┆ 2017-04-17 15:18:04 │
│           ┆                      ┆ 1117                     ┆              ┆                     │
└───────────┴──────────────────────┴──────────────────────────┴──────────────┴─────────────────────┘

In [16]:
webdata2 = pl.read_csv(config["input_data"]["file2"])
webdata2.head()

shape: (5, 2)
┌───────────┬───────────┐
│ client_id ┆ Variation │
│ ---       ┆ ---       │
│ i64       ┆ str       │
╞═══════════╪═══════════╡
│ 9988021   ┆ Test      │
│ 8320017   ┆ Test      │
│ 4033851   ┆ Control   │
│ 1982004   ┆ Test      │
│ 9294070   ┆ Control   │
└───────────┴───────────┘

In [ ]:
webdata2["Variation"].value_counts()

shape: (3, 2)
┌───────────┬───────┐
│ Variation ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ NA        ┆ 20109 │
│ Control   ┆ 23532 │
│ Test      ┆ 26968 │
└───────────┴───────┘

In [35]:
webdata1["process_step"].value_counts().sort("count", descending=True)

shape: (5, 2)
┌──────────────┬────────┐
│ process_step ┆ count  │
│ ---          ┆ ---    │
│ str          ┆ u32    │
╞══════════════╪════════╡
│ start        ┆ 108910 │
│ step_1       ┆ 73432  │
│ step_2       ┆ 61768  │
│ step_3       ┆ 53628  │
│ confirm      ┆ 45403  │
└──────────────┴────────┘